### ISSUE TITLE
As a user, I want to see where the lines run through Cochabamba

### ISSUE THREAD

**Issue by christophhanser** [trufi-association/trufi-app#285] opened 2019-06-17 17:37 UTC
We could start with a simple view on the maps, with the rendered lines

**Comment by mdoelker** [comment] 2019-10-05 19:52
Duplicate of #21

**Closed by mdoelker** 2019-10-05 19:52 UTC

**Comment by christophhanser** [comment] 2019-10-06 08:07
It is still one of the very difficult ones, because displaying the routes
in the screen was not supported oufothebox.

This issue was rather General about showing the routes of whole Cochabamba.

Issue #21 was about directly in the beginning showing the routes nearby the
users Position. This is one of my most wanted features because users would
directly know what options they have!

Christoph

**Comment by christophhanser** [comment] 2020-03-28 20:56
@mdoelker , Could this be done in an extra map layer from our new maptile server?

**Comment by mdoelker** [comment] 2020-03-31 12:50
Let's continue this in #21, which will essentially be the same thing

**Comment by christophhanser** [comment] 2020-03-31 20:33
Yes!

We need a map where the routes are visible.
When the User opens the App she would directly see, which routes are
running nearby her Position.
